"""update Message model

Revision ID: ba33b508a032
Revises: 5dc8f37d0392
Create Date: 2025-02-06 14:25:58.353238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba33b508a032'
down_revision: Union[str, None] = '5dc8f37d0392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
