name: Tests

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
      - master
      - development
      - production

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      DB_NAME: chat
      DB_USER: ""
      DB_PASSWORD: ""
      DB_HOST: 127.0.0.1
      DB_PORT: 27017

    services:
      mongo_checkpoints:
        image: mongo:latest
        env:
          ME_CONFIG_MONGODB_ADMINUSERNAME: ""
          ME_CONFIG_MONGODB_ADMINPASSWORD: ""
          ME_CONFIG_BASICAUTH: false
        ports:
          - 127.0.0.1:27017:27017

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Poetry install dependencies
        run: |
          pip install --upgrade pip setuptools wheel poetry && \
          poetry config virtualenvs.create false && \
          poetry install

      - name: Run tests Users
        run: | 
          cd users && \
          python -m pytest